### ISSUE TITLE
Long description causes crash when adding document

### ISSUE THREAD

**Issue by robertwflynn** [roman-yagodin/R7.Documents#23]
Add document crashes with the following error when adding a document with a lengthy description.

Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: String or binary data would be truncated. The statement has been terminated. ---> System.Data.SqlClient.SqlException: String or binary data would be truncated. The statement has been terminated. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at PetaPoco.Database.Update(String tableName, String primaryKeyName, Object poco, Object primaryKeyValue, IEnumerable`1 columns) at PetaPoco.Database.Update(Object poco, Object primaryKeyValue, IEnumerable`1 columns) at PetaPoco.Database.Update(Object poco) at DotNetNuke.Data.PetaPoco.PetaPocoRepository`1.UpdateInternal(T item) at DotNetNuke.Data.RepositoryBase`1.Update(T item) at R7.Documents.ControllerBase.Update[T](T info) at R7.Documents.EditDocuments.Update(Boolean Override) --- End of inner exception stack trace ---

**Comment by roman-yagodin** [comment]
I'm aware of it - just need to add max. length check for text area field. Will be fixed in next release.

Thanks for feedback :+1:

**Comment by roman-yagodin** [comment]
Pre-release of v1.0.8 available at https://github.com/roman-yagodin/R7.Documents/releases/tag/v1.0.8. Please let me know if it works for you.

**Comment by robertwflynn** [comment]
It works great!!!  Great improvement over the old documents!  The ability to add longer descriptions is a real plus!

Thanks!


Bob
[cid:image001.jpg@01D0BB2B.8037C1F0]
Robert W. Flynn
President/CEO
Christian Military Fellowship
bob@CMFHQ.org
(800) 798-7875 (Toll Free)
(303) 761-1959 (Office)
(303) 619-1460 (Cell)

**Comment by roman-yagodin** [comment]
Thanks! :smile: 
Closing this.
