### ISSUE TITLE
DNN8: Unknown server tag 'dnnweb:DnnDateTimePicker'

### ISSUE THREAD

**Issue by khswsoft** [roman-yagodin/R7.Documents#41]
Using your module on a DNN8 site results in a fatal error, Unknown server tag 'dnnweb:DnnDateTimePicker'

We hope you will be able to fix this so we can continue using your module!

The complete stacktrace here below:
DotNetNuke.Services.Exceptions.ModuleLoadException: Unknown server tag 'dnnweb:DnnDateTimePicker'. ---> System.Web.HttpParseException: Unknown server tag 'dnnweb:DnnDateTimePicker'. ---> System.Web.HttpParseException: Unknown server tag 'dnnweb:DnnDateTimePicker'. ---> System.Web.HttpException: Unknown server tag 'dnnweb:DnnDateTimePicker'. at System.Web.UI.TagPrefixTagNameToTypeMapper.System.Web.UI.ITagNameToTypeMapper.GetControlType(String tagName, IDictionary attribs) at System.Web.UI.MainTagNameToTypeMapper.GetControlType(String tagName, IDictionary attribs, Boolean fAllowHtmlTags) at System.Web.UI.ControlBuilder.CreateChildBuilder(String filter, String tagName, IDictionary attribs, TemplateParser parser, ControlBuilder parentBuilder, String id, Int32 line, VirtualPath virtualPath, Type& childType, Boolean defaultProperty) at System.Web.UI.TemplateParser.ProcessBeginTag(Match match, String inputText) at System.Web.UI.TemplateParser.ParseStringInternal(String text, Encoding fileEncoding) --- End of inner exception stack trace --- at System.Web.UI.TemplateParser.ProcessException(Exception ex) at System.Web.UI.TemplateParser.ParseStringInternal(String text, Encoding fileEncoding) at System.Web.UI.TemplateParser.ParseString(String text, VirtualPath virtualPath, Encoding fileEncoding) --- End of inner exception stack trace --- at System.Web.UI.TemplateParser.ParseString(String text, VirtualPath virtualPath, Encoding fileEncoding) at System.Web.UI.TemplateParser.ParseFile(String physicalPath, VirtualPath virtualPath) at System.Web.UI.TemplateParser.ParseInternal() at System.Web.UI.TemplateParser.Parse() at System.Web.Compilation.BaseTemplateBuildProvider.get_CodeCompilerType() at System.Web.Compilation.BuildProvider.GetCompilerTypeFromBuildProvider(BuildProvider buildProvider) at System.Web.Compilation.BuildProvidersCompiler.ProcessBuildProviders() at System.Web.Compilation.BuildProvidersCompiler.PerformBuild() at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath) at DotNetNuke.UI.ControlUtilities.LoadControl[T](TemplateControl containerControl, String ControlSrc) at DotNetNuke.UI.Modules.WebFormsModuleControlFactory.CreateModuleControl(TemplateControl containerControl, ModuleInfo moduleConfiguration) at DotNetNuke.UI.Modules.ModuleControlFactory.LoadModuleControl(TemplateControl containerControl, ModuleInfo moduleConfiguration) at DotNetNuke.UI.Modules.ModuleHost.LoadModuleControl() --- End of inner exception stack trace ---

**Comment by roman-yagodin** [comment]
DNN 8 isn't supported yet, sorry. You can get experimental package for DNN8 is here: https://github.com/roman-yagodin/R7.Documents/releases/download/v1.7.0/R7.Documents-01.07.00-Install-DNN8-Experimental.zip and see if it works for you.

**Comment by khswsoft** [comment]
Thank you for the quick response.
I've installed this package without issues.

Kind regards,
Ken

Op 2016-09-12 12:54, schreef Roman M. Yagodin:

**Comment by roman-yagodin** [comment]
The [v1.8.0 release](https://github.com/roman-yagodin/R7.Documents/releases/tag/v1.8.0) officially supports DNN 8.0.4. Closing this.
