### ISSUE TITLE
Review "optimize stored procedures" patch

### ISSUE THREAD

**Issue by roman-yagodin** [roman-yagodin/R7.Documents#6]
Need to review "optimize stored procedures" patch by @sleupold to original DNN Documents module. Patch source: https://dnndocuments.codeplex.com/SourceControl/list/patches

**Comment by roman-yagodin** [comment]
[dnndocuments.txt](https://github.com/roman-yagodin/R7.Documents/files/1051458/dnndocuments.txt)

**Comment by sleupold** [comment]
Userdisplayname function has been added to DNN 7.2.1.
Regarding existence check, I usually prefer now 
IF Exists (SELECT * FROM sys.procedures WHERE Name Like N'...')
which is easiest to read IMO.

**Comment by roman-yagodin** [comment]
Thanks for clearing this up, Sebastian!
