### ISSUE TITLE
impossible to keep the original file

### ISSUE THREAD

**Issue by ProjectMarco** [roman-yagodin/R7.Documents#85]
Hi Roman, and thanx for your amazing module.
Unfortunately I have a problem when I want to keep an original file.

When I load a first file and want to overwrite it with a second that has the same name everything works.

But if I want to load a second file with the same name as the first one (which I guess is renamed with _1 or (1)) but keeping the first, if I click on the option the upload will not start and the "Loading file stopped" message will appear.

This happens both as a host and with other roles to which I have given all the necessary permissions, to the module and to the folder.

![keepfile_option_img1](https://user-images.githubusercontent.com/50585561/57628303-f907e100-7599-11e9-9a63-2546555a479f.jpg)

![keepfile_option_img2](https://user-images.githubusercontent.com/50585561/57628314-fc9b6800-7599-11e9-9bd1-0b039a0c1576.jpg)

Thanx for your reply.

Regards.

Marco

**Comment by roman-yagodin** [comment]
Thanks for your feedback, @ProjectMarco! But file upload component is part of the DNN Platform, not the R7.Documents module. You can report bugs here: https://github.com/dnnsoftware/Dnn.Platform/issues
